CREATE DATABASE SIMPLE_CMS; 
USE SIMPLE_CMS; 
CREATE TABLE TBL_USERS (
    USER_ID int NOT NULL AUTO_INCREMENT,
    USERNAME varchar(255) NOT NULL,
    USER_PASS varchar(64),
	USER_TYPE BOOLEAN,
    PRIMARY KEY (USER_ID),
	UNIQUE (USERNAME));
INSERT INTO TBL_USERS (USERNAME, USER_PASS,USER_TYPE) VALUES ("admin","c1c224b03cd9bc7b6a86d77f5dace40191766c485cd55dc48caf9ac873335d6f",TRUE); 
CREATE TABLE TBL_POSTS (
    POST_ID int NOT NULL AUTO_INCREMENT,
	USER_ID int NOT NULL,
    POST_TITLE varchar(50),
    POST_BODY TEXT,
	POST_TIME DATETIME,
    PRIMARY KEY (POST_ID),
	FOREIGN KEY (USER_ID) REFERENCES TBL_USERS(USER_ID));